#!/bin/sh
#SPRING_PROFILES_ACTIVE=development ./gradlew -DserviceKey=QO8Jo5UWN4rASy9NIoiUXwQBSbOmphw6UT41sDCNzo8bBQDmJuseGioU3KK94sgHrXmliI5SGphq1akyyWJ5Qg== clean bootTestRun
SPRING_PROFILES_ACTIVE=development ./gradlew -DserviceKey=IfJN7A3cBBPttYf%2FFcFWC8pNDT3mi3SRSsDJmyAXQAUOlqvkQhP4ggZkHzhacIhEEJzcswWo8fraVeUBAOxQng== clean bootTestRun
